var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/arcade/vaults/reveal/route.js")
R.c("server/chunks/[root-of-the-server]__75a64b35._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_b09f0f56.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_arcade_vaults_reveal_route_actions_83c681f8.js")
R.m(691272)
module.exports=R.m(691272).exports
