var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/evacuate/route.js")
R.c("server/chunks/[root-of-the-server]__f5513195._.js")
R.c("server/chunks/node_modules_ccxt_js_src_static_dependencies_dydx-v4-client_43d7d57f._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_b6cfe300._.js")
R.c("server/chunks/_59fb7ad0._.js")
R.c("server/chunks/_next-internal_server_app_api_exchange_evacuate_route_actions_89aeb3bf.js")
R.m(529549)
module.exports=R.m(529549).exports
