var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/p2p/payment-methods/route.js")
R.c("server/chunks/[root-of-the-server]__6a7a561c._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_p2p_payment-methods_route_actions_cd1d67fd.js")
R.m(52884)
module.exports=R.m(52884).exports
