var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/cron/twap/route.js")
R.c("server/chunks/[root-of-the-server]__6519e612._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_67f08ccd.js")
R.c("server/chunks/node_modules_ccxt_js_src_static_dependencies_dydx-v4-client_43d7d57f._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/src_app_api_exchange_orders_route_ts_a9c1ba05._.js")
R.c("server/chunks/[root-of-the-server]__37b578a9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_59fb7ad0._.js")
R.c("server/chunks/_b6cfe300._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/_next-internal_server_app_api_exchange_cron_twap_route_actions_5f8ad2ba.js")
R.m(394380)
module.exports=R.m(394380).exports
