var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/status/route.js")
R.c("server/chunks/[root-of-the-server]__79e91be7._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__6ba75e6e._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_status_route_actions_9253a7ee.js")
R.m(546497)
module.exports=R.m(546497).exports
