var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/account/passkeys/register/verify/route.js")
R.c("server/chunks/[root-of-the-server]__ad103f14._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/_00eca53a._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/ce889_server_app_api_account_passkeys_register_verify_route_actions_7413ef04.js")
R.m(422118)
module.exports=R.m(422118).exports
