var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/password-reset/confirm/route.js")
R.c("server/chunks/[root-of-the-server]__a925980d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__6ba75e6e._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/_next-internal_server_app_api_auth_password-reset_confirm_route_actions_a82451da.js")
R.m(530074)
module.exports=R.m(530074).exports
