var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/trades/route.js")
R.c("server/chunks/[root-of-the-server]__6f5b6dbd._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_cd67e8d7.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_trades_route_actions_8c92768e.js")
R.m(37061)
module.exports=R.m(37061).exports
