// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(v2shell)/admin/arcade-transparency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/arcade-transparency">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/admin/arcade-transparency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/admin/markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/markets">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/admin/markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/arcade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arcade">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/arcade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/arcade/transparency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arcade/transparency">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/arcade/transparency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connections">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/support/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/api">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/support/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/support/fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/fees">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/support/fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/support/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/help">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/support/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/trades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trades/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/trades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trades">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(v2shell)/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/order-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-history">> = Specific
  const handler = {} as typeof import("../../../src/app/order-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/p2p/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p2p/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/p2p/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/p2p/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p2p/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/p2p/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/p2p/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p2p">> = Specific
  const handler = {} as typeof import("../../../src/app/p2p/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminal">> = Specific
  const handler = {} as typeof import("../../../src/app/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/account">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/markets">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/p2p/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/p2p/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/p2p/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/p2p/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/p2p/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/p2p/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/p2p/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/p2p">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/p2p/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/trade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/trade">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/trade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v2/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/wallet/withdraw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/withdraw">> = Specific
  const handler = {} as typeof import("../../../src/app/wallet/withdraw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/kyc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/kyc">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/kyc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/notification-preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/notification-preferences">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/notification-preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/notification-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/notification-schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/notification-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/passkeys/authenticate/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/passkeys/authenticate/options">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/passkeys/authenticate/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/passkeys/authenticate/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/passkeys/authenticate/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/passkeys/authenticate/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/passkeys/register/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/passkeys/register/options">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/passkeys/register/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/passkeys/register/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/passkeys/register/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/passkeys/register/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/passkeys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/passkeys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/passkeys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/sessions/logout-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/sessions/logout-all">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/sessions/logout-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/totp/disable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/totp/disable">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/totp/disable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/totp/enable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/totp/enable">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/totp/enable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/totp/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/totp/setup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/totp/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/totp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/totp/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/totp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/verify-email">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/account-timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/account-timeline">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/account-timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/arcade/transparency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/arcade/transparency">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/arcade/transparency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/assets/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/assets/seed">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/assets/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/email/outbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/outbox">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/email/outbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/email/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/email/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/explain/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/explain/order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/explain/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/explain/p2p-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/explain/p2p-order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/explain/p2p-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/explain/withdrawal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/explain/withdrawal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/explain/withdrawal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/notifications-deferred/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications-deferred">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/notifications-deferred/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/run-notifications-digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/run-notifications-digest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/run-notifications-digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/risk-simulate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/risk-simulate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/risk-simulate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/actions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/ai/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/ai/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/ai/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/ai/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/ai/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/ai/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/badge-pools/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/badge-pools/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/badge-pools/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/calendar/daily/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/calendar/daily/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/calendar/daily/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/calendar/daily/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/calendar/daily/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/calendar/daily/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/calendar/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/calendar/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/calendar/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/community/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/community/claim">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/community/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/community/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/community/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/community/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/crafting/craft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/crafting/craft">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/crafting/craft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/crafting/salvage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/crafting/salvage">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/crafting/salvage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/creation/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/creation/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/creation/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/creation/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/creation/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/creation/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/cron/resolve-ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/cron/resolve-ready">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/cron/resolve-ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/daily/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/daily/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/daily/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/daily/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/daily/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/daily/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/draft/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/draft/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/draft/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/draft/pick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/draft/pick">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/draft/pick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/draft/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/draft/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/draft/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/fusion/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/fusion/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/fusion/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/fusion/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/fusion/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/fusion/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/insight/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/insight/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/insight/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/insight/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/insight/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/insight/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/missions/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/missions/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/missions/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/missions/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/missions/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/missions/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/missions/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/missions/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/missions/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/mutation/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/mutation/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/mutation/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/mutation/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/mutation/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/mutation/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/progression/prestige-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/progression/prestige-reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/progression/prestige-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/progression/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/progression">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/progression/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/safety/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/safety">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/safety/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/season/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/season">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/season/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/shared-pool/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/shared-pool/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/shared-pool/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/shared-pool/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/shared-pool/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/shared-pool/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/shared-pool/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/shared-pool/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/shared-pool/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/streak/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/streak/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/streak/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/streak/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/streak/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/streak/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/transparency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/transparency">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/transparency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/vaults/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/vaults/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/vaults/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/vaults/hint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/vaults/hint">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/vaults/hint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/vaults/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/vaults/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/vaults/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/wheel/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/wheel/commit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/wheel/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/wheel/reveal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/wheel/reveal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/wheel/reveal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/assets/icon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/icon">> = Specific
  const handler = {} as typeof import("../../../src/app/api/assets/icon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/password-reset/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password-reset/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/password-reset/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/password-reset/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password-reset/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/password-reset/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/email-notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/email-notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/email-notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/notifications-digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/notifications-digest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/notifications-digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/ops-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/ops-alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/ops-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/price-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/price-alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/price-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/kyc-approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/kyc-approve">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/kyc-approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/whoami/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/whoami">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/whoami/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/account-timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/account-timeline">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/account-timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/audit-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/audit-log">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/audit-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/balances-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/balances-summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/balances-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/deposits/credit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/deposits/credit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/deposits/credit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/deposits/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/deposits/finalize">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/deposits/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/deposits/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/deposits/lookup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/deposits/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/kyc-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/kyc-review">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/kyc-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/markets/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/markets/[id]/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/markets/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/markets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/outbox/dead-letters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/outbox/dead-letters">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/outbox/dead-letters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/reconciliation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/reconciliation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/reconciliation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/transfers/[id]/reverse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/transfers/[id]/reverse">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/transfers/[id]/reverse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/withdrawals/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/withdrawals/[id]/approve">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/withdrawals/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/withdrawals/[id]/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/withdrawals/[id]/broadcast">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/withdrawals/[id]/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/withdrawals/[id]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/withdrawals/[id]/reject">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/withdrawals/[id]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/admin/withdrawals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/admin/withdrawals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/admin/withdrawals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/arbitrage/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/arbitrage/execute">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/arbitrage/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/arbitrage/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/arbitrage/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/arbitrage/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/arbitrage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/arbitrage">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/arbitrage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/balances">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/conditional-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/conditional-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/conditional-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/connections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/connections/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/connections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/connections">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/convert/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/convert/execute">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/convert/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/convert/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/convert/quote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/convert/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/copy-trading/leaders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/copy-trading/leaders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/copy-trading/leaders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/copy-trading/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/copy-trading/subscriptions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/copy-trading/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/conditional-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/conditional-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/conditional-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/finalize-deposits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/finalize-deposits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/finalize-deposits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/outbox-worker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/outbox-worker">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/outbox-worker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/recurring-buys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/recurring-buys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/recurring-buys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/scan-deposits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/scan-deposits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/scan-deposits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/sweep-deposits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/sweep-deposits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/sweep-deposits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/cron/twap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/cron/twap">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/cron/twap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/deposit-address/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/deposit-address">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/deposit-address/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/deposit/address/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/deposit/address">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/deposit/address/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/deposits/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/deposits/pending">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/deposits/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/deposits/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/deposits/report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/deposits/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/deposits/trace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/deposits/trace">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/deposits/trace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/dev/credit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/dev/credit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/dev/credit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/dev/deposit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/dev/deposit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/dev/deposit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/dev/seed-assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/dev/seed-assets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/dev/seed-assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/dev/seed-execution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/dev/seed-execution">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/dev/seed-execution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/dev/seed-markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/dev/seed-markets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/dev/seed-markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/dev/seed-open-book/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/dev/seed-open-book">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/dev/seed-open-book/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/evacuate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/evacuate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/evacuate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/funding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/funding">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/funding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/gas/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/gas/quote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/gas/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/holds/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/holds/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/holds/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/holds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/holds">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/holds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/marketdata/candles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/marketdata/candles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/marketdata/candles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/marketdata/depth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/marketdata/depth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/marketdata/depth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/marketdata/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/marketdata/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/marketdata/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/marketdata/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/marketdata/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/marketdata/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/marketdata/top/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/marketdata/top">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/marketdata/top/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/marketdata/trades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/marketdata/trades">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/marketdata/trades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/markets/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/markets/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/markets/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/markets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/orders/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/orders/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/orders/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/orders/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/orders/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/orders/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/portfolio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/portfolio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/recurring-buys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/recurring-buys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/recurring-buys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/tickers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/tickers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/tickers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/transfers/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/transfers/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/transfers/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/twap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/twap">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/twap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/tx/[hash]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/tx/[hash]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/tx/[hash]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/withdrawals/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/withdrawals/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/withdrawals/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/withdrawals/allowlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/withdrawals/allowlist">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/withdrawals/allowlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/withdrawals/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/withdrawals/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/withdrawals/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/withdrawals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange/withdrawals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/withdrawals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/explain/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/explain/order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/explain/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/explain/p2p-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/explain/p2p-order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/explain/p2p-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/explain/withdrawal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/explain/withdrawal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/explain/withdrawal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/express/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/express/quote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/express/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/db">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/home/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/home/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/intelligence/regime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence/regime">> = Specific
  const handler = {} as typeof import("../../../src/app/api/intelligence/regime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/market/band/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/band">> = Specific
  const handler = {} as typeof import("../../../src/app/api/market/band/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/market/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/snapshot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/market/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/admin/disputes/[id]/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/admin/disputes/[id]/resolve">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/admin/disputes/[id]/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/admin/disputes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/admin/disputes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/admin/disputes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/ads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/ads">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/ads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/cron/expire-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/cron/expire-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/cron/expire-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/fiats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/fiats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/fiats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/orders/[id]/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/orders/[id]/action">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/orders/[id]/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/orders/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/orders/[id]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/orders/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/orders/[id]/dispute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/orders/[id]/dispute">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/orders/[id]/dispute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/orders/[id]/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/orders/[id]/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/orders/[id]/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/payment-methods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/payment-methods">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/payment-methods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/reference/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/reference">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/reference/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/p2p/reputation/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/p2p/reputation/[userId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/p2p/reputation/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/system/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/version">> = Specific
  const handler = {} as typeof import("../../../src/app/api/system/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/dispute/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/dispute/decision">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/dispute/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/dispute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/dispute">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/dispute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/evidence">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/evidence/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/evidence/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/evidence/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/proof-pack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/proof-pack">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/proof-pack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/risk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/status/awaiting-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/status/awaiting-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/status/awaiting-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/status/canceled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/status/canceled">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/status/canceled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/status/paid-marked/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/status/paid-marked">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/status/paid-marked/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/status/released/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/status/released">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/status/released/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/[id]/status/resolved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/[id]/status/resolved">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/[id]/status/resolved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trading/bot/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/bot/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trading/bot/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trading/bot/[id]/stop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/bot/[id]/stop">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trading/bot/[id]/stop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trading/bot/cross-exchange/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/bot/cross-exchange">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trading/bot/cross-exchange/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trading/bot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/bot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trading/bot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/watchlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/watchlist">> = Specific
  const handler = {} as typeof import("../../../src/app/api/watchlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/whoami/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whoami">> = Specific
  const handler = {} as typeof import("../../../src/app/api/whoami/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(v2shell)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(v2shell)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/v2/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/v2">> = Specific
  const handler = {} as typeof import("../../../src/app/v2/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
