var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/admin/transfers/[id]/reverse/route.js")
R.c("server/chunks/[root-of-the-server]__6519e612._.js")
R.c("server/chunks/node_modules_ccxt_js_src_static_dependencies_dydx-v4-client_43d7d57f._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__058e2d03._.js")
R.c("server/chunks/_59fb7ad0._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/_b6cfe300._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/ce889_server_app_api_exchange_admin_transfers_[id]_reverse_route_actions_d40c2bff.js")
R.m(684093)
module.exports=R.m(684093).exports
