var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/admin/wallet/route.js")
R.c("server/chunks/[root-of-the-server]__fff1ee56._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_ee8b84ab.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_59fb7ad0._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_exchange_admin_wallet_route_actions_52217599.js")
R.m(379829)
module.exports=R.m(379829).exports
