var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/account/password/route.js")
R.c("server/chunks/[root-of-the-server]__3caf10da._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__6ba75e6e._.js")
R.c("server/chunks/_next-internal_server_app_api_account_password_route_actions_06be9360.js")
R.m(104563)
module.exports=R.m(104563).exports
