var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/p2p/orders/[id]/action/route.js")
R.c("server/chunks/[root-of-the-server]__c722a1f2._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_c6dffd64.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_p2p_orders_[id]_action_route_actions_1d2deb4d.js")
R.m(518810)
module.exports=R.m(518810).exports
