var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/arcade/wheel/reveal/route.js")
R.c("server/chunks/[root-of-the-server]__2ceabc95._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_2090526c.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/_next-internal_server_app_api_arcade_wheel_reveal_route_actions_2e41cf0f.js")
R.m(59860)
module.exports=R.m(59860).exports
