var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__09fb36c8._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_a87a9ace.js")
R.c("server/chunks/ssr/[root-of-the-server]__a3edf894._.js")
R.c("server/chunks/ssr/node_modules_next_dist_274ac3eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/src_app_0db9afea._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9e1f531d._.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_aa661ba4._.js")
R.c("server/chunks/ssr/src_9f5a3f90._.js")
R.c("server/chunks/ssr/_5b825777._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(895193)
module.exports=R.m(895193).exports
