var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/explain/order/route.js")
R.c("server/chunks/[root-of-the-server]__b2334e2c._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__a44c2f34._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_formdata-node_lib_esm_File_ccf0a600.js")
R.c("server/chunks/_next-internal_server_app_api_explain_order_route_actions_783300db.js")
R.m(512698)
module.exports=R.m(512698).exports
