var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/reset/route.js")
R.c("server/chunks/[root-of-the-server]__27c48dd1._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_784a7e9d.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_reset_route_actions_ff43f9b8.js")
R.m(498253)
module.exports=R.m(498253).exports
