var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/password-reset/request/route.js")
R.c("server/chunks/[root-of-the-server]__482f18b0._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__6ba75e6e._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_password-reset_request_route_actions_1d9c9d41.js")
R.m(923248)
module.exports=R.m(923248).exports
