var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/copy-trading/subscriptions/route.js")
R.c("server/chunks/[root-of-the-server]__6519e612._.js")
R.c("server/chunks/[root-of-the-server]__d72feaf8._.js")
R.c("server/chunks/node_modules_ccxt_js_src_static_dependencies_dydx-v4-client_43d7d57f._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_b6cfe300._.js")
R.c("server/chunks/_59fb7ad0._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/ce889_server_app_api_exchange_copy-trading_subscriptions_route_actions_f1bd2b42.js")
R.m(577248)
module.exports=R.m(577248).exports
