var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/arbitrage/route.js")
R.c("server/chunks/[root-of-the-server]__8752dc6e._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_ccxt_js_src_static_dependencies_dydx-v4-client_43d7d57f._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_b6cfe300._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_exchange_arbitrage_route_actions_bb0f05c5.js")
R.m(542497)
module.exports=R.m(542497).exports
