var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/intelligence/regime/route.js")
R.c("server/chunks/[root-of-the-server]__b3630f85._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0cd03ead.js")
R.c("server/chunks/_b6cfe300._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_ccxt_js_src_static_dependencies_dydx-v4-client_43d7d57f._.js")
R.c("server/chunks/_next-internal_server_app_api_intelligence_regime_route_actions_7e3522c7.js")
R.m(434750)
module.exports=R.m(434750).exports
