var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/p2p/admin/disputes/[id]/resolve/route.js")
R.c("server/chunks/[root-of-the-server]__3e48a224._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_7642bbc9.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/ce889_server_app_api_p2p_admin_disputes_[id]_resolve_route_actions_2f5e2022.js")
R.m(606680)
module.exports=R.m(606680).exports
