var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/exchange/deposit/address/route.js")
R.c("server/chunks/[root-of-the-server]__060a4cb6._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/src_lib_db_ts_86d9618b._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/_59fb7ad0._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/_next-internal_server_app_api_exchange_deposit_address_route_actions_a75d914b.js")
R.m(367305)
module.exports=R.m(367305).exports
